
name: Update README
on: 
schedule:
    - cron: '*/30 * * * *'
workflow_dispatch: 
jobs: 
build: 
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v2 
- uses: GrimReaper007-Sharon/GrimReaper007-Sharon@master 
env: GITHUB_TOKEN:${{ secrets.GITHUB_TOKEN }} 
with: 
COMMIT_MSG: 'Specify a custom commit message' 
MAX_LINES:10




  
  
    
  
    

  
  


  
  
    
    

    
   
      

      
      
        

      
      
        
          
          
